//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace Initialization.Resources
{
	public static class ResKeys
	{
		public static readonly ComponentResourceKey ApplyButton = new ComponentResourceKey(typeof(Resources), nameof(ApplyButton));
		public static readonly ComponentResourceKey ConnectionStringTitle = new ComponentResourceKey(typeof(Resources), nameof(ConnectionStringTitle));
		public static readonly ComponentResourceKey ConnectionWatermark = new ComponentResourceKey(typeof(Resources), nameof(ConnectionWatermark));
		public static readonly ComponentResourceKey DatabaseTypeTitle = new ComponentResourceKey(typeof(Resources), nameof(DatabaseTypeTitle));
		public static readonly ComponentResourceKey ExampleText = new ComponentResourceKey(typeof(Resources), nameof(ExampleText));
		public static readonly ComponentResourceKey ExampleTilte = new ComponentResourceKey(typeof(Resources), nameof(ExampleTilte));
		public static readonly ComponentResourceKey Title = new ComponentResourceKey(typeof(Resources), nameof(Title));
	}
}