//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace SignIn.Resources
{
	public static class ResKeys
	{
		public static readonly ComponentResourceKey AutoLabel = new ComponentResourceKey(typeof(Resource), nameof(AutoLabel));
		public static readonly ComponentResourceKey EmptyWarning = new ComponentResourceKey(typeof(Resource), nameof(EmptyWarning));
		public static readonly ComponentResourceKey ErrorInput = new ComponentResourceKey(typeof(Resource), nameof(ErrorInput));
		public static readonly ComponentResourceKey Forget = new ComponentResourceKey(typeof(Resource), nameof(Forget));
		public static readonly ComponentResourceKey NameHint = new ComponentResourceKey(typeof(Resource), nameof(NameHint));
		public static readonly ComponentResourceKey PasswordHint = new ComponentResourceKey(typeof(Resource), nameof(PasswordHint));
		public static readonly ComponentResourceKey SignInBtn = new ComponentResourceKey(typeof(Resource), nameof(SignInBtn));
	}
}