//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace nTestSystem.Desktop.Resources
{
	public static class ResKeys
	{
		public static readonly ComponentResourceKey SignInLabel = new ComponentResourceKey(typeof(Resource), nameof(SignInLabel));
		public static readonly ComponentResourceKey Title = new ComponentResourceKey(typeof(Resource), nameof(Title));
	}
}