//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace TopWindow.Resources
{
	public static class ResKeys
	{
		public static readonly ComponentResourceKey DataAnalysis = new ComponentResourceKey(typeof(Resource), nameof(DataAnalysis));
		public static readonly ComponentResourceKey MainMenu = new ComponentResourceKey(typeof(Resource), nameof(MainMenu));
		public static readonly ComponentResourceKey Setting = new ComponentResourceKey(typeof(Resource), nameof(Setting));
		public static readonly ComponentResourceKey System = new ComponentResourceKey(typeof(Resource), nameof(System));
		public static readonly ComponentResourceKey Tools = new ComponentResourceKey(typeof(Resource), nameof(Tools));
		public static readonly ComponentResourceKey TopWindowTitle = new ComponentResourceKey(typeof(Resource), nameof(TopWindowTitle));
	}
}