//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace DataConnection.Resources
{
	public static class ResKeys
	{
		public static readonly ComponentResourceKey ApplyBtn = new ComponentResourceKey(typeof(Resource), nameof(ApplyBtn));
		public static readonly ComponentResourceKey ConnectionLabel = new ComponentResourceKey(typeof(Resource), nameof(ConnectionLabel));
		public static readonly ComponentResourceKey DatabaseTypeLabel = new ComponentResourceKey(typeof(Resource), nameof(DatabaseTypeLabel));
		public static readonly ComponentResourceKey ExampleLabel = new ComponentResourceKey(typeof(Resource), nameof(ExampleLabel));
		public static readonly ComponentResourceKey LocationLabel = new ComponentResourceKey(typeof(Resource), nameof(LocationLabel));
	}
}