//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace ProfileDetails.Resources
{
	public static class ResKeys
	{
		public static readonly ComponentResourceKey Description = new ComponentResourceKey(typeof(Resource), nameof(Description));
		public static readonly ComponentResourceKey Filter = new ComponentResourceKey(typeof(Resource), nameof(Filter));
		public static readonly ComponentResourceKey UploadPhoto = new ComponentResourceKey(typeof(Resource), nameof(UploadPhoto));
	}
}