//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace nTestSystem.Resources
{
	public static class ResKeys
	{
		public static readonly ComponentResourceKey Test2 = new ComponentResourceKey(typeof(Resources), nameof(Test2));
		public static readonly ComponentResourceKey Title = new ComponentResourceKey(typeof(Resources), nameof(Title));
	}
}